# Generated by Django 3.1 on 2020-09-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacao',
            old_name='Item',
            new_name='conjunto',
        ),
    ]
