# Generated by Django 3.1 on 2020-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço Venda'),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='relacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço'),
        ),
    ]
