# Generated by Django 3.1 on 2020-09-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Componente')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Compra')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço Venda')),
                ('fator', models.DecimalField(decimal_places=4, default=2.0, max_digits=5, verbose_name='Fator de Conversão')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Conjunto')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjuntos',
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Tipo de Componente')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
            },
        ),
        migrations.CreateModel(
            name='TipoConjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Tipo do Conjunto')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Conjunto',
                'verbose_name_plural': 'Tipos de Conjunto',
            },
        ),
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço')),
                ('Item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conjunto.conjunto')),
                ('componente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conjunto.componente')),
            ],
            options={
                'verbose_name': 'Relação',
                'verbose_name_plural': 'Realações',
            },
        ),
        migrations.AddField(
            model_name='conjunto',
            name='lista',
            field=models.ManyToManyField(through='conjunto.Relacao', to='conjunto.Componente'),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.tipoconjunto'),
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.tipocomponente'),
        ),
    ]
