# Generated by Django 3.1 on 2020-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cad',
            field=models.URLField(blank=True, verbose_name='CAD'),
        ),
        migrations.AddField(
            model_name='item',
            name='datasheet',
            field=models.URLField(blank=True, verbose_name='DataSheet'),
        ),
    ]
