# Generated by Django 3.1 on 2020-08-30 02:13

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('nivel', models.IntegerField(verbose_name='Nivel de Acesso')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('juiz', models.CharField(max_length=100, verbose_name='juiz')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Vara Judicial',
                'verbose_name_plural': 'Varas Judiciais',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('senha', models.CharField(max_length=10, verbose_name='Senha')),
                ('token', models.CharField(blank=True, default='', max_length=255, verbose_name='token')),
                ('img', stdimage.models.StdImageField(blank=True, upload_to='usuarios', verbose_name='Imagem')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.CharField(max_length=100, verbose_name='numero')),
                ('intimacao', models.DateField(blank=True, verbose_name='intimação')),
                ('inicio', models.DateField(blank=True, verbose_name='inicio do trabalho')),
                ('entrega', models.DateField(blank=True, verbose_name='entrega')),
                ('requerente', models.CharField(max_length=100, verbose_name='Requerente')),
                ('requerido', models.CharField(max_length=100, verbose_name='Requerido')),
                ('honorario_pro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Honorário Proposto')),
                ('honorario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Honorário')),
                ('obs', models.TextField(blank=True, max_length=1000, verbose_name='obs')),
                ('vara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vara', verbose_name='Vara')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
