# Generated by Django 3.1 on 2020-08-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='E-Mail'),
        ),
        migrations.DeleteModel(
            name='Processo',
        ),
        migrations.DeleteModel(
            name='Vara',
        ),
    ]
