# Generated by Django 3.1 on 2020-09-06 03:04

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_industria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, upload_to='cliente/logo', verbose_name='Imagem'),
        ),
    ]
