# Generated by Django 3.1 on 2020-09-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.IntegerField(blank=True, verbose_name='Telefone'),
        ),
    ]
