# Generated by Django 3.1 on 2020-09-01 01:08

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Fabricante')),
                ('pais', models.CharField(blank=True, default='', max_length=20, verbose_name='Nacionalidade')),
                ('img', stdimage.models.StdImageField(blank=True, upload_to='fabricante', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Família')),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Linha')),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('codigo', models.CharField(help_text='Imforme o codigo do produto', max_length=20, unique=True, verbose_name='Código de Cadastro')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Código de Identificação')),
                ('descricao', models.CharField(blank=True, max_length=50, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço Compra')),
                ('img', stdimage.models.StdImageField(blank=True, upload_to='itens', verbose_name='Imagem')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.fabricante')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.familia')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.linha')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.tipo')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
