# Generated by Django 3.1 on 2020-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200905_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de Cadastro'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
    ]
