# Generated by Django 3.1 on 2020-09-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('core', '0001_initial'),
        ('conjunto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(upload_to='propostas/files', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.arquivo')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
            },
        ),
        migrations.CreateModel(
            name='ItemConjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.conjunto')),
            ],
            options={
                'verbose_name': 'Item Montado',
                'verbose_name_plural': 'Itens Montados',
            },
        ),
        migrations.CreateModel(
            name='ItemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='TipoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Tipo do Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Tipo do Arquivo',
                'verbose_name_plural': 'Tipos de Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=20, verbose_name='Vendedor')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('projeto', models.CharField(max_length=200, verbose_name='Projeto')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('datafinal', models.DateField(verbose_name='Data final')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('conjuntos', models.ManyToManyField(through='proposta.ItemConjunto', to='conjunto.Conjunto')),
                ('documentos', models.ManyToManyField(through='proposta.Arquivos', to='proposta.Arquivo')),
                ('items', models.ManyToManyField(through='proposta.ItemProduto', to='item.Item')),
                ('responsavel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.responsavel')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.tipo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.vendedor')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
        migrations.AddField(
            model_name='itemproduto',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.proposta'),
        ),
        migrations.AddField(
            model_name='itemconjunto',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.proposta'),
        ),
        migrations.AddField(
            model_name='arquivos',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.proposta'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposta.tipoarquivo'),
        ),
    ]
